name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: psr

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check
      run: make -C psr check


    - name: Format
      run: make -C psr format

    - name: Test
      run: make -C psr test

    - name: Release
      run: make -C psr release

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4 #v3 is scheduled for deprecation Nov 30 2024 check marketplace
      with:
        name: release-binary
        path: ${{ env.WORKING_DIR }}/target/release/psr